import { NgModule } from '@angular/core';
import { MatCarouselModule } from '@ngmodule/material-carousel';
import {MatButtonModule, MatCheckboxModule,
  MatInputModule, MatFormFieldModule,
  MatCardModule,
  MatTabsModule,
  MatListModule,
  MatBadgeModule,
  MatIconModule,
  MatDialogModule,
  MatTooltipModule,
  MatChipsModule,
  MatProgressSpinnerModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatRadioModule,
  MatSelectModule,
  MatToolbarModule,
  MatMenuModule,
  MatExpansionModule,
  MatPaginatorModule,

} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatFormFieldModule,
    MatCardModule,
    MatTabsModule,
    MatListModule,
    MatBadgeModule,
    MatIconModule,
    MatDialogModule,
    MatTooltipModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSelectModule,
    MatToolbarModule,
    MatMenuModule,
    MatCarouselModule,
    MatExpansionModule,
    MatPaginatorModule
  ],
  exports: [MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatFormFieldModule,
    MatCardModule,
    MatTabsModule,
    MatListModule,
    MatBadgeModule,
    MatIconModule,
    MatDialogModule,
    MatTooltipModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSelectModule,
    MatToolbarModule,
    MatMenuModule,
    MatCarouselModule,
    MatExpansionModule,
    MatPaginatorModule
  ],
})
export class AngMaterialModule { }
